version: '3.1'
services:
  app:
    container_name: pwabay-backend
    image: p17513/pwabay:latest
    ports:
      - 3000:3000
    depends_on:
      - mysql
  postgres:
    container_name: mysql
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=pwa_bay_mysql
      - MYSQL_USER=root
    ports:
      - 3307:3306
    volumes:
      - pwabay:/var/lib/mysql/data
volumes:
  pwabay:
